### ISSUE TITLE
I can't signup

### ISSUE THREAD

**Issue by Dann1y** [NikValdez/FullStackTwitterClone#1]
![image](https://user-images.githubusercontent.com/29726020/114505141-e6f1ba00-9c6a-11eb-85f9-abe2965c970b.png)

I had cloned this repository and launched these FE, BE server.
and I can't signup.

I checked the console, there is an message

`Warning: An unhandled error was caught from submitForm() Error: Not Authorised!`

Let me know if I don't know or something is wrong!

**Comment by russelshane** [comment]
Maybe make sure that you have the right PostgreSQL config
